name: CDelivery pipeline for ECS

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  graasp-deploy-ecs-workflow:
    name: CD caller template
    uses: graasp/graasp-deploy/.github/workflows/cdelivery-ecs.yml@main
    with:
      ecs-task-definition: '.aws/<name>-prod.json'
    secrets:
      aws-access-key-id:
      aws-secret-access-key:
      aws-region:
      ecs-cluster:
      ecs-service:
      container-name:
      ecr-repository:
      next-public-api-host:
      next-public-google-analytics-id:
      next-public-graasp-auth-host:
      next-public-graasp-perform-host:
      next-public-graasper-id:
      next-public-published-tag-id:
      port: