name: CD S3-apps template caller workflow

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    name: CD caller template
    uses: graasp/graasp-deploy/.github/workflows/cdelivery-s3-apps.yml@7ae32139ebc4e9e69f9d522f8a0f47734505ec64
    with:
      build-folder: 'build'
      version: 'latest'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_<NAME> }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_<NAME> }}
      aws-region: ${{ secrets.AWS_REGION_<NAME> }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_<NAME>_PROD }}
      app-id: ${{ secrets.APP_ID }}
      graasp-domain-prod: ${{ secrets.GRAASP_DOMAIN_PROD }}
      cloudfront-distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_<NAME>_PROD }}

