name: CD ECS template caller workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push tag event
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 'latest'

jobs:
  call-reusable-workflow:
    name: Graasp test
    uses: graasp/graasp-deploy/.github/workflows/cdeployment-ecs.yml@7ae32139ebc4e9e69f9d522f8a0f47734505ec64
    with:
      ecs-task-definition: '.aws/<name>-test.json'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_<NAME> }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_<NAME> }}
      aws-region: ${{ secrets.AWS_REGION_<NAME> }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER_<NAME>_TEST }}
      ecs-service: ${{ secrets.ECS_SERVICE_<NAME>_TEST }}
      container-name: ${{ secrets.CONTAINER_NAME_<NAME>_TEST }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_<NAME>_TEST }}