name: Deploy to development environment

# Control when the action will run
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches:
      - main
      - master

  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      test-execution:
        type: boolean
        default: true
        description: 'Execute test job (Default: yes)'

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-s3-workflow:
    # Replace with repository name
    name: CI caller template
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cintegration-s3.yml@main
    # Replace input build-folder if needed
    with:
      build-folder: 'build'
      # Test values
      enable-mock-api-test:
      graasper-id-test:
      graasp-app-id-test:
      graasp-authentication-host-test:
      graasp-compose-host-test:
      graasp-domain-test:
      hidden-item-tag-id-test:
      mock-api-test:
      next-public-api-host-test:
      next-public-google-analytics-id-test:
      next-public-graasp-perform-host-test:
      next-public-graasp-authentication-host-test:
      next-public-node-env-test:
      next-public-published-tag-id-test:
      node-env-test: 
      public-tag-id-test:
      test-execution: ${{ inputs.test-execution }}
    # Insert required secrets based on repository with the following format: ${{ secrets.SECRET_NAME }}
    secrets:
      api-host:
      api-host-test:
      authentication-host:
      aws-access-key-id:
      aws-region:
      aws-s3-bucket-name:
      aws-secret-access-key:
      cloudfront-distribution-id:
      domain:
      ga-measurement-id:
      google-key:
      graasp-analyzer-host:
      graasp-compose-host:
      graasp-explorer-host:
      graasp-perform-host:
      hidden-item-tag-id:
      port:
      show-notifications:
      stripe-publishable-key:
      graasp-analyzer-host:
      google-key:
      h5p-integration-url:
      hidden-item-tag-id:
      port:
      sentry-dsn:
      show-notifications:
