name: CI S3-apps caller workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #branches:
  #  - master

  #pull_request:
  #  branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    name: Graasp
    uses: victorggonzalez/workflows/.github/workflows/s3-cintegration.yml@main
    with:
      build-folder: 'build'
      version: 'latest'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_<NAME> }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_<NAME> }}
      aws-region: ${{ secrets.AWS_REGION_<NAME> }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_<NAME>_<ENVIRONMENT> }}
      app-id: ${{ secrets.APP_ID }}
      graasp-domain-dev: ${{ secrets.GRAASP_DOMAIN_<ENVIRONMENT> }}
      cloudfront-distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_<NAME>_<ENVIRONMENT> }}

