name: Deploy to development environment

# Controls when the action will run
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches:
      - main
      - master

  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-ecs-workflow:
    # Replace with repository name
    name: CI caller template
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    uses: graasp/graasp-deploy/.github/workflows/cintegration-ecs.yml@main
    # Replace input ecs-task-definition with template file. Format: '.aws/<name>-dev.json'
    with:
      ecs-task-definition:
    # Insert required secrets based on repository with the following format: ${{ secrets.SECRET_NAME }}
    secrets:
      aws-access-key-id:
      aws-secret-access-key:
      aws-region:
      ecs-cluster:
      ecs-service:
      container-name:
      ecr-repository:
