name: CI pipeline for S3

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main

  pull_request:
   branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  graasp-deploy-s3-workflow:
    name: CI caller template
    uses: graasp/graasp-deploy/.github/workflows/cintegration-s3.yml@main
    with:
      build-folder: 'build'
    secrets:
      aws-access-key-id:
      aws-secret-access-key:
      aws-region:
      aws-s3-bucket-name:
      cloudfront-distribution:
      api-host:
      show-notifications:
      graasp-compose-host: