name: Publish package to NPM

description: "Publish new package version to the NPM registry"

inputs:
  npm-token:
    description: 'NPM auth token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'

    - name: Ensure clean install
      run: yarn install --immutable
      shell: bash

    - name: Publish to NPM
      run: npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
