# This workflow creates a new YYYYMMddhhmm-staging-versions.json file inside the staging-versions folder
# with the latest tag pushed by the repository that triggered the workflow.
name: Update staging stack

# Controls when the action will run
on:
  # Triggers the workflow on repository_dispatch events but only for the update-staging-version event
  repository_dispatch:
    types: [update-staging-version]

# This workflow is made up of one job called create
jobs:
  # Create a new YYYYMMddhhmm-staging-versions.json file with latest pushed tag.
  create:
    name: Create staging-versions.json file
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Check-out repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Check out code
      uses: actions/checkout@v3

    # Get the latest modified file in the staging-versions working directory.
    - name: Get latest versions file
      id: latest-file
      run: |
        cd ./staging-versions
        LATEST_FILE_NAME=$(ls -Ar | head -n 1)
        echo "latest=${LATEST_FILE_NAME}" >> $GITHUB_OUTPUT

    # Create new staging-versions.json file. Use jq to write to stdout and pipe the output to a newly created file.
    # If the file already contains the repository, update the tag value
    # If the file does not contain the repository, include both the repository and tag
    - name: Create new staging-versions.json file
      # Set environment variables required to create the file. These are only available to this step
      env:
        # REPOSITORY: repository that will update current version.
        REPOSITORY: ${{ github.event.client_payload.repository }}
        # TAG: tag pushed by the repository.
        TAG: ${{ github.event.client_payload.tag }}
        # LATEST_FILE_NAME: latest staging-versions.json file created. It will be used as template.
        LATEST_FILE_NAME: ${{ steps.latest-file.outputs.latest }}
      run: |
        FILE_NAME=$(echo "`date +"%Y%m%d%H%M"`"-staging-versions.json)
        echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
        jq --arg tag "$TAG" --arg repository "$REPOSITORY" \
        'if ((.include[] | select(.repository == $repository)) // null) != null then (.include[] | select(.repository == $repository) | .tag) |= $tag else .include += [{"repository": $repository, "tag": $tag}] end' \
        ./staging-versions/$LATEST_FILE_NAME > ./staging-versions/$FILE_NAME

    # Detect changed files during a Workflow run and commit and push them back to the GitHub repository
    - name: Commit step
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
         # Commit message for the created commit.
        commit_message: 'chore: updated staging stack ${{ env.FILE_NAME }}'
